development:
  clients:
    default:
      database: spiritual-door-development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: spiritual-door-test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
